<a href="https://colab.research.google.com/github/Nesferus1/dz_shill_repo/blob/main/%D0%90%D0%B4%D0%B0%D0%BF%D1%82%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BA%D1%83%D1%80%D1%81_%D0%BF%D0%BE_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B5_%D0%94%D0%97_2_%D0%9A%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F_%D1%87%D0%B0%D1%81%D1%82%D1%8C_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Задача 1. (1 балл)

Сделайте задания ниже, используя библиотеки numpy и/или scipy.

1. Найдите определитель матрицы

$$ \begin{pmatrix} 1 & 6 & 4 & 2 & 4 \\ 4 & 3 & 1 & 34 & 1 \\ 45 & 4 & 1 & 3 & 4 \\ 12 & 7 & 11 & 2 & 0 \\ 43 & 42 & 10 & 1 & 2 \end{pmatrix}$$

In [3]:
matrix = np.array([
    [1, 6, 4, 2, 4],
    [4, 3, 1, 34, 1],
    [45, 4, 1, 3, 4],
    [12, 7, 11, 2, 0],
    [43, 42, 10, 1, 2]
])
det = np.linalg.det(matrix)

print("Определитель матрицы:", det)

Определитель матрицы: 2366668.9999999986


2. Найдите матрицу, обратную матрице

$$ \begin{pmatrix} 1 & 12 & 3 & 2 \\ 4 & 30 & 0 & 1 \\ 12 & 4 & 3 & 5 \\ 1 & 5 & 1 & 10  \end{pmatrix}$$


In [4]:
matrix = np.array([
    [1, 12, 3, 2],
    [4, 30, 0, 1],
    [12, 4, 3, 5],
    [1, 5, 1, 10]
])
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обратная матрица:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матрица не является обратимой.")

Обратная матрица:
[[-7.43236448e-02  2.34335714e-02  8.41798250e-02 -2.95685407e-02]
 [ 1.09624862e-02  3.03731268e-02 -1.10630594e-02  3.01719803e-04]
 [ 3.35311274e-01 -1.26018304e-01  1.94106407e-02 -6.41657447e-02]
 [-3.15800060e-02 -4.92809011e-03 -4.82751685e-03  1.09222569e-01]]


3. Найдите собственные значения матрицы
$$ \begin{pmatrix} 1 & 10 & 3 & 12 \\ 3 & 20 & 0 & 2 \\ 11 & 3 & 3 & 6 \\ 1 & 8 & 1 & 10   \end{pmatrix}$$


In [5]:
matrix = np.array([
    [1, 10, 3, 12],
    [3, 20, 0, 2],
    [11, 3, 3, 6],
    [1, 8, 1, 10]
])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Собственные значения матрицы:")
print(eigenvalues)

Собственные значения матрицы:
[24.07073984 -3.82947026  4.1150109   9.64371953]


4. Найдите спектральное разложение матрицы

$$ \begin{pmatrix} 1 & 10 & 3 & 12 \\ 3 & 20 & 0 & 2 \\ 11 & 3 & 3 & 6 \\ 1 & 8 & 1 & 10   \end{pmatrix}$$

In [6]:
matrix = np.array([
    [1, 10, 3, 12],
    [3, 20, 0, 2],
    [11, 3, 3, 6],
    [1, 8, 1, 10]
])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

D = np.diag(eigenvalues)

A_reconstructed = eigenvectors @ D @ np.linalg.inv(eigenvectors)

print("Собственные значения:")
print(eigenvalues)
print("\nСобственные векторы:")
print(eigenvectors)
print("\nСпектральное разложение (A = VDV^(-1)):")
print(A_reconstructed)

Собственные значения:
[24.07073984 -3.82947026  4.1150109   9.64371953]

Собственные векторы:
[[-0.52393658 -0.51316051  0.19831329  0.43097922]
 [-0.58401432  0.07006812 -0.01518686 -0.17116613]
 [-0.47136585  0.85294691  0.96393249  0.85289473]
 [-0.40278031 -0.06510238 -0.1768484   0.23985338]]

Спектральное разложение (A = VDV^(-1)):
[[ 1.0000000e+00  1.0000000e+01  3.0000000e+00  1.2000000e+01]
 [ 3.0000000e+00  2.0000000e+01 -4.4408921e-16  2.0000000e+00]
 [ 1.1000000e+01  3.0000000e+00  3.0000000e+00  6.0000000e+00]
 [ 1.0000000e+00  8.0000000e+00  1.0000000e+00  1.0000000e+01]]


### Задача 2 (0.5)

Рассмотрим задачу:

Сколько существует 5-значных чисел, которые начинаются с цифры 2 или 4, содержат только четные цифры и при этом каждая цифра повторяется не более трёх раз?

1. Приведите "математическое" решение этой задачи. (0.1).
2. Напишите код на python, который перебирает все числа, проверяет, удовлетворяют ли они условию и в конце выводит количество нужных чисел. (0.4)

In [11]:
def count_valid_numbers():
    even_digits = ['0', '2', '4', '6', '8']
    count = 0

    # Первая цифра может быть 2 или 4
    for first_digit in ['2', '4']:
        # Перебираем оставшиеся 4 цифры
        for second_digit in even_digits:
            for third_digit in even_digits:
                for fourth_digit in even_digits:
                    for fifth_digit in even_digits:
                        # Формируем число
                        num_str = first_digit + second_digit + third_digit + fourth_digit + fifth_digit
                        # Проверяем, что каждая цифра не повторяется более трех раз
                        if all(num_str.count(digit) <= 3 for digit in even_digits):
                            count += 1

    return count

result = count_valid_numbers()
print("Количество 5-значных чисел, удовлетворяющих условиям:", result)

Количество 5-значных чисел, удовлетворяющих условиям: 1208


### Задача 3 (1 балл)


*Это задача на "отлично (превосходит ожидания)" по шкале перевода оценок НИУ ВШЭ:  https://www.hse.ru/studyspravka/Scale*

*Но она на самом деле не такая уж сложная.*



a. (0.8). Напишите свою функцию-реализацию метода Гаусса для решения систем линейных уравнений.

Программа должна принимать на вход Матрицу A и вектор-столбец b и решать систему уравнений $Ax=b$.

Вы можете самостотельно определить формат входных и выходных данных. Например, вы можете хранить A как двумерный numpy массив A или список списков, вектор-столбец b - как одномерный numpy-массив или список (list). Программа должна возвращать вектор x. Отдельно подумайте над ситуациями, когда решений нет или бесконечно много.

Разрешено использовать numpy, но только для операций над массивами (нельзя использовать numpy.linalg, за исключением numpy.linalg.det, если понадобится).

b. (0.2).Напишите свою функцию-реализацию метода Крамера для решения систем линейных уравнений.

Все дополнительные условия - как в п.а. Если система не может быть решена методом Крамера, функция должна вывести соответствующее сообщение.



### Задача 4 (1 балл)

*Это задача на "отлично (существенно превосходит ожидания)" по шкале перевода оценок НИУ ВШЭ:  https://www.hse.ru/studyspravka/Scale*.

*Даже из команды курса за неё не все готовы были бы взяться.*

Система может находиться в одном из двух состояний $A$ или $B$. Экспериментатор умеет измерять косвенную величину $x$, которая поможет ему определить состояние, в котором находится система. Тем не менее, метод, которым экспериментатор измеряет величину $x$ обладает погрешностью. Будем считать, что функция распределения величины $x$ имеет гауссов вид, причем среднее значение равно $\pm \tilde x$ для состояний $A$ и $B$ соответственно, а дисперсия равна $\sigma^2$ и не зависит от состояния:

\begin{equation}
  P(x\ |\ A) = \frac{1}{\sqrt{2 \pi \sigma}}\exp\left(\frac{-(x-\tilde x)^2}{2 \sigma^2}\right), \quad P(x\ |\ B) = \frac{1}{\sqrt{2 \pi \sigma}}\exp\left(\frac{-(x+\tilde x)^2}{2 \sigma^2}\right).
\end{equation}

В случае, когда $\sigma \gg \tilde x$ погрешность метода слишком велика и отдельное измерение не позволяет достоверно определить состояние, в котором находится система. Пусть $\tilde x = 1$, $\sigma = 10$ и каждое измерение не изменяет состояния системы. Предлагается выполнить $N$ измерений, чтобы определить состояние системы.

In [ ]:
X_MEAN = 1
SIGMA = 10

1. (0.3 Балла) Пусть априорные вероятности нахождения системы в состояниях A и B равны друг другу, $P(A) = P(B) = 1/2$. Сгенерируйте состояние системы, а затем проведите $N$ измерений величины $x$ в соотвествии с вероятностями, приведенными выше, получится массив $\{x_1,x_2, \dots, x_N\}$. Изобразите результат на графике, по оси абсцисс отложите $i$ (номер измерения), а по оси ординат $x_i/\tilde x$. Можно ли определить состояние системы по этому графику? Каким выбрать параметр $N$?

In [ ]:
#your code here

2. (0.7 Баллов) Попробуем теперь вычислить вероятность нахождения системы в состоянии $A$ при условии проведенных измерений. Вероятность после первого измерения выражается с помощью формулы Байеса как
\begin{equation}
  P(A\ |\ x_1) = \frac{P(x_1\ |\ A) P(A)}{P(x_1)}, \quad P(x_1) = P(x_1\ |\ A) P(A) + P(x_1\ |\ B) P(B).
\end{equation}
В соответствии с этими формулами мы можем обновлять наше знание о вероятности нахождения системы в состоянии $A$ и $B$. В начале следующего шага $P(A) = P(A\ |\ x_1)$, $P(B) = 1 - P(A\ |\ x_1)$ и нам нужно будет учесть аналогичным образом уже измерение $x_2$, чтобы получить обновленнные вероятности. Постройте график $P(A)$ в зависимости от номера шага и прокомментируйте его. Подберите хорошее значение для параметра $N$, объясните свой выбор. Сравните результаты с первым пунктом.

In [ ]:
#your code here